version: '3.2'
services:
  db:
    image: mongo:4.2
    container_name: desafio-tindin-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: tindinauth
      MONGO_INITDB_ROOT_USERNAME: tindinauth
      MONGO_INITDB_ROOT_PASSWORD: tindinauth
 
  # backend:
  #   container_name: desafio-tindin-node
  #   restart: always
  #   build: '.'
  #   depends_on: 
  #     - db
  #   ports:
  #     - 3000:3000